<a href="https://colab.research.google.com/github/Rafarbm/Ciencia_Dados_Aprendizagem_Maquina/blob/main/Unidade3_ProjetoCienciaDados/ProjetoCienciaDados_30_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Criando o DataFrame das cidades

In [1]:
import pandas as pd
cidades = pd.DataFrame(
    [
        ['Paraná', 'Londrina', 575377, 1356.00],
        ['São Paulo', 'São Carlos', 254484, 1508.00],
        ['Santa Catarina', 'Florianópolis', 508826, 1798.00],
        ['Paraná', 'Curitiba', 1963726, 2293.00],
        ['São Paulo', 'Campinas', 1223237, 1710.00]
    ],
    columns=['Estado', 'Cidade', 'Habitantes', 'Salário-Médio']
)

print("--- DataFrame Original ---")
display(cidades)

--- DataFrame Original ---

           Estado         Cidade  Habitantes  Salário-Médio
0          Paraná       Londrina      575377         1356.0
1       São Paulo     São Carlos      254484         1508.0
2  Santa Catarina  Florianópolis      508826         1798.0
3          Paraná       Curitiba     1963726         2293.0
4       São Paulo       Campinas     1223237         1710.0

Funções Básicas

In [2]:
print("\n--- Primeiras linhas (head) ---")
display(cidades.head(2))

print("\n--- Últimas linhas (tail) ---")
display(cidades.tail(2))

print("\n--- Dimensões (shape) ---")
print(cidades.shape)

print("\n--- Informações Gerais (info) ---")
cidades.info()

print("\n--- Estatísticas do Salário Médio ---")
display(cidades['Salário-Médio'].describe())

--- Primeiras linhas (head) ---

      Estado      Cidade  Habitantes  Salário-Médio
0     Paraná    Londrina      575377         1356.0
1  São Paulo  São Carlos      254484         1508.0

--- Últimas linhas (tail) ---

      Estado    Cidade  Habitantes  Salário-Médio
3     Paraná  Curitiba     1963726         2293.0
4  São Paulo  Campinas     1223237         1710.0

--- Dimensões (shape) ---
(5, 4)

--- Informações Gerais (info) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Estado         5 non-null      object
 1   Cidade         5 non-null      object
 2   Habitantes     5 non-null      int64
 3   Salário-Médio  5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

--- Estatísticas do Salário Médio ---

count       5.000000
mean     1733.000000
std       357.459089
min      1356.000000
25%      1508.000000
50%      1710.000000
75%      1798.000000
max      2293.000000
Name: Salário-Médio, dtype: float64

Usando os tipos de dados e datas

In [3]:
cidades['Habitantes'] = cidades['Habitantes'].astype('float64')

# Adicionando coluna de data
cidades['Data'] = ['3-8-2021', '3-9-2021', '3-10-2021', '3-11-2021', '3-12-2021']
cidades['Data'] = pd.to_datetime(cidades['Data'], format='%d-%m-%Y')

In [4]:
cidades['Data'] = cidades['Data'].dt.strftime('%d-%m-%Y')

Colunas

In [5]:
cidades.rename(columns={'Habitantes': 'N Habitantes', 'Data': 'Data - Censo'}, inplace=True)

Adicionando e Removendo Colunas

In [6]:
cidades.insert(2, 'Sigla', ['PR', 'SP', 'SC', 'PR', 'SP'])
cidades.insert(2, 'Sigla-Repetida', cidades['Sigla'])

In [ ]:
cidades = cidades.drop(['Sigla-Repetida'], axis=1)

Consultas

In [8]:
print("\n--- Consulta: Salário maior que 1400.0 ---")
display(cidades.query('`Salário-Médio` > 1400.0'))

--- Consulta: Salário maior que 1400.0 ---

,Estado,Cidade,Sigla-Repetida,Sigla,N Habitantes,Salário-Médio,Data - Censo
1,São Paulo,São Carlos,SP,SP,254484.0,1508.0,03-09-2021
2,Santa Catarina,Florianópolis,SC,SC,508826.0,1798.0,03-10-2021
3,Paraná,Curitiba,PR,PR,1963726.0,2293.0,03-11-2021
4,São Paulo,Campinas,SP,SP,1223237.0,1710.0,03-12-2021

Ordenação

In [10]:
cidades.sort_values(by='Salário-Médio', inplace=True)
print("\n--- Ordenado por Salário-Médio ---")
display(cidades)

--- Ordenado por Salário-Médio ---

,Estado,Cidade,Sigla-Repetida,Sigla,N Habitantes,Salário-Médio,Data - Censo
0,Paraná,Londrina,PR,PR,575377.0,1356.0,03-08-2021
1,São Paulo,São Carlos,SP,SP,254484.0,1508.0,03-09-2021
4,São Paulo,Campinas,SP,SP,1223237.0,1710.0,03-12-2021
2,Santa Catarina,Florianópolis,SC,SC,508826.0,1798.0,03-10-2021
3,Paraná,Curitiba,PR,PR,1963726.0,2293.0,03-11-2021

In [ ]:
Combinando DataFrames

In [12]:
cidades_salarios = pd.DataFrame([
    ['Paraná', 'Londrina', 1356.00],
    ['São Paulo', 'São Carlos', 1508.00],
    ['Santa Catarina', 'Florianópolis', 1798.00],
    ['Paraná', 'Curitiba', 2293.00],
    ['São Paulo', 'Campinas', 1710.00]
], columns=['Estado', 'Cidade', 'Salário-Médio'])

cidades_pop = pd.DataFrame([
    ['Londrina', 575377],
    ['São Carlos', 254484],
    ['Florianópolis', 508826],
    ['Curitiba', 1963726],
    ['Campinas', 1223237]
], columns=['Cidade', 'Habitantes'])

print("\n--- Teste de Merge (Inner Join) ---")
display(pd.merge(left=cidades_salarios, right=cidades_pop, on="Cidade"))

--- Teste de Merge (Inner Join) ---

           Estado         Cidade  Salário-Médio  Habitantes
0          Paraná       Londrina         1356.0      575377
1       São Paulo     São Carlos         1508.0      254484
2  Santa Catarina  Florianópolis         1798.0      508826
3          Paraná       Curitiba         2293.0     1963726
4       São Paulo       Campinas         1710.0     1223237

Salvando Arquivos

In [14]:
cidades.to_csv("my_df.csv", index=False)
print("\nArquivo 'my_df.csv' salvo com sucesso no ambiente do Colab!")

Arquivo 'my_df.csv' salvo com sucesso no ambiente do Colab!